name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/cache@v1
      id: cache
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
          
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd SimpleRss/
        carthage bootstrap --platform ios --cache-builds
          
    - name: Build
      run: swift build -v
    - name: Run tests
      run: |
        cd SimpleRss/
        xcodebuild test \
            -project SimpleRss.xcodeproj \
            -scheme SimpleRss \
            -destination 'platform=iOS Simulator,name=iPhone SE,OS=13.3'
